import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'

const Home: NextPage = () => {

  type props = {
    title: string
    imageUrl: string
    explanation: string
    prioptionce: string
    price: string
  }

const [hoge,setHoge]=useState<Array<props>>([]);

const test =  async() => {
  const MetaData = await axios.get("https://abe-masafumi.github.io/TestMetaData/MetaData.json");
  setHoge(MetaData.data)
  return MetaData.data;
} 

useEffect(()=>{
  (async()=>{
    const data= await test();
    console.log(data)
  })()
},[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* {JSON.stringify(hoge)} */}
        {
          hoge.map((item, index) => (
           <li key={index}>
             <img src={item.imageUrl} />
              <p>{item.title}</p>
              <p>{item.explanation}</p>
              <p>{item.price}</p>
              <p>{item.prioptionce}</p>
            </li>
          ))
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
